server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_0d537f05e054
    token: 0821

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml