server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_0d537f05e054
    token: 0821
    app-id: wx1a604f4dc2fb7ca9
    app-secret: 4d4441e61d531c4fad1f4699c3cbc3d1
    template-id: OpNRXXxdsLzdfywJfyAaP97vpBj-s5RLPu4Ta0ASLVI

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000159601215
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCXrsyae4xx45lvi5/EkwUe1Lq3FPN8zD3WBgGVYaSNMpIF9d2vlkzdB6zvwhDRZSulfF2z9FXf2yegXyT1klocukHnrLg0uiG3dOCfdYvmHiGTVk4a4smdA3OIRL0xLAremvYh70MgV0ffL15Yt9Gtkc/lxgcfQrQDKX1Ab8lggUrvt+wHVJCxNwPhrVjhnUjvSsF7WNVVHlEnz1zojdFfvgriysY5BKS2gtcKOR0saQYkDe3XTOS8ormisJnXbazadAcEschJQAtTP1/P4BM9tUuoVxkuTayoxZoD4G7uy1vStxT/tN3UY4QzU9wTsgGNod4zSdOTplvI+guN/NCXAgMBAAECggEALqQZVgdXkE2kCKCuaAutL2XKZDGVDXLgMMd4BS8ZIjHCpQKNQEi/KdgKXU8XTMwHN8OeLI+dOFBzRuT6wGhYPS0oxsxdeBkj9P2DdIT4l7H8MQoAylOiGx3MkMJSSqR4UyrjNFwWEAPGneI66JzdZLnJa6YQ2pPwNmizkvTMv1eFQaIazEfmdfJcpwrz7/vuPhU1Ydr6knxlRLuuvfooYbadlTdo6QmnQAgEkQ6QnUa1HSwPFrDotFBBO21Fl0ZcLho4FWs/rgl5+hhtTwWSqRJD4tXx6fbhO/0aZm2VhrianU//L0+yYAxBlh9XyqVx+f6/ogn2WchW1T35Zlf1QQKBgQD+aP24ilEZYBjRv6t/q6VnYOuVeTjZasxtE/pEGetzUK8yL66w0AYYMhLceMU/3SGOHsvNehqMnUt6tYpwKXj5JNuh2nZxRG75uEO3S3LEiFduqYghC96iJ26Tr6vyESoUsnv1AhZkigCUBfeDlyD4yjsqaeM1xR9cEIbAhoQskwKBgQCYoXaqAbR3ciLwdqsFR6c2FbIoXJGmLH4aIQgr5F8CV236mDdx/Lp0aQHbjt9Df4+YFekL5ubxt5EaZTC4GoutQAhPa9dGB9nO/nIp5XHb/POZcyYa/nKOr7QI0yNdNHGY9m3Hr2FFxMN2s7Ndiu5fDWB7eZpXBr560oHx2M6SbQKBgQCsBCFJXXxoQ+mEKKy0rkIwHAAuGMCvgN6oAhH9aekhFzTeIg9jzcPRKEpIeAAmpkXB6mCylhTNbq1SUt0/6Uq6aol2blgXTcYbYtOmY4U+DVHQqSA59+SYj0Dc6rLAAYsKY4QcrUSmxgiODVrFxrGshlBq5R2Tha0meqYiFtHXsQKBgEHUUgPdHGLwHVWtOPHcB6hyDxcNZdxQEEtgt8+GfdvarZqJkFBfemO+7ogtxOmt2Nb1jEAP5MeYLsM9pZeiC2A739mxX3Xa6Pw4DjE3vrXtEXu7iFHYMLyN145+0h/fAKfCkXKwl7mptcw6kT/lLg5dDKH0vraOOBVtOZJ/ugi5AoGBANL4JSs27G1Xtce7mPgKoBred0IeSXaxctN6+1ruCysuBqGVp0MnSJnO1CP2tqWyKgnkXtl980dm6jqK9OdlhGGsuDqCfYnelAL5MCCt3JjyBnNA2o0/YEG+BWYJE2pwEmqY/4nZ0BHrD8Ka7J2Clmb12vr2ZOWlcQD8DHybWQ0q
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvgN5yEjsWIk/avF5EfXij6rustV4GMkoMil7T1G460AOnNZx7q3tYufpjuHd3dAxiFmPoYwfINnKNy+M9UJhxqqhRWf07RLkq+mR9mlmRjlwe2+RyA1l0MJpUTkJAk9z6LLbH1cuqIC9Xf1xJsmlHocCP6L4cX1LKeEmqOOFF6rExZcDZGitzNwxUKiru/YdaCXkrzDBKjgV2X35FJ2OwC1kC72uRRGV92FHb9bVDpMVE+b6m6+xZa4m609aaWFXD0A8JokXo3gyYXNzPlPtLF1JIEs2j0xxh+69j4ZCeS5sRDwXkoaHqcd66Yu9TXCBGLDyqRU5sSVfXBYS0EdwRwIDAQAB
  notify_url: http://xfg-studio.natapp1.cc/api/v1/alipay/pay_notify
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml